apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: customer-profiles-frontend
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: customer-profiles-frontend
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: clusterBuilder
      value: default
  build:
    env:
      - name: BP_NODE_RUN_SCRIPTS
        value: "build"
      - name: BP_WEB_SERVER_ROOT
        value: "dist"
  source:
    git:
      url: https://github.com/carlosonunez-vmw/awesome-web-app-frontend
      ref:
        branch: main
